## SLURM PROLOG ###############################################################
##    Job ID : 3530829
##  Job Name : ccv_script.sh
##  Nodelist : gpu2103
##      CPUs : 1
##  Mem/Node : 24576 MB
## Directory : /gpfs/home/bli31/2951x/cs2951x_final/model
##   Started : Mon Dec  6 02:54:01 EST 2021
###############################################################################
module: unloading 'java/8u111'
module: loading 'java/8u111'
module: unloading 'matlab/R2017b'
module: loading 'matlab/R2017b'
module: unloading 'intel/2017.0'
module: loading 'intel/2017.0'
module: loading 'scikit-learn/0.21.2'
module: scikit-learn: To use: module load python/3.5.2
module: loading 'tensorflow/1.14.0_gpu_py36'
module: tensorflow: Make sure you request a GPU node first to use tensorflow with GPU support. To use: module load cuda/10.0.130 cudnn/7.4 python/3.6.6_test
module: loading 'cudnn/7.4'
module: cudnn: To use: module load cuda/10.0.130
module: unloading 'python/2.7.12'
module: loading 'python/3.6.6_test'
module: loading 'cuda/10.0.130'
module: loading 'keras/2.1.3_py3'
module: keras: To use: module load tensorflow/<version>_gpu_py3 python/3.5.2
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W1206 02:54:18.393798 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:68: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1206 02:54:18.496269 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:504: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1206 02:54:18.498862 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:3828: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1206 02:54:18.741854 140292976289600 deprecation.py:323] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:2731: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W1206 02:54:18.990057 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/optimizers.py:744: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1206 02:54:19.004027 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:3005: The name tf.log is deprecated. Please use tf.math.log instead.

W1206 02:54:20.297766 140292976289600 deprecation_wrapper.py:119] From /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:973: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

2021-12-06 02:54:20.444919: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-06 02:54:20.478879: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-12-06 02:54:20.720511: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b8b4b0 executing computations on platform CUDA. Devices:
2021-12-06 02:54:20.720601: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 3090, Compute Capability 8.6
2021-12-06 02:54:20.728711: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400095000 Hz
2021-12-06 02:54:20.729422: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5d5e590 executing computations on platform Host. Devices:
2021-12-06 02:54:20.729438: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-12-06 02:54:20.731635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 3090 major: 8 minor: 6 memoryClockRate(GHz): 1.695
pciBusID: 0000:61:00.0
2021-12-06 02:54:20.739264: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2021-12-06 02:54:20.797492: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2021-12-06 02:54:20.823258: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2021-12-06 02:54:20.846600: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2021-12-06 02:54:20.906888: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2021-12-06 02:54:20.927958: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2021-12-06 02:54:21.053686: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-12-06 02:54:21.057802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-12-06 02:54:21.057845: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2021-12-06 02:54:21.060276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-12-06 02:54:21.060296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-12-06 02:54:21.060316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2021-12-06 02:54:21.064286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22805 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3090, pci bus id: 0000:61:00.0, compute capability: 8.6)
2021-12-06 02:59:03.817522: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2021-12-06 03:00:30.948357: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
0.25.3
here
here
Epoch 1/50
Traceback (most recent call last):
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(128, 256), b.shape=(256, 256), m=128, n=256, k=256
	 [[{{node lstm_1/while/MatMul_4}}]]
	 [[loss/mul/_151]]
  (1) Internal: Blas GEMM launch failed : a.shape=(128, 256), b.shape=(256, 256), m=128, n=256, k=256
	 [[{{node lstm_1/while/MatMul_4}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model.py", line 203, in <module>
    main(sys.argv)
  File "model.py", line 168, in main
    prep_data(data, nl_word_to_idx, rl_word_to_idx, source_words, target_words, rl_idx_to_word)
  File "model.py", line 97, in prep_data
    validation_steps = val_samples//batch_size)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/engine/training.py", line 2177, in fit_generator
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/engine/training.py", line 1849, in train_on_batch
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py", line 2475, in __call__
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(128, 256), b.shape=(256, 256), m=128, n=256, k=256
	 [[node lstm_1/while/MatMul_4 (defined at /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:1072) ]]
	 [[loss/mul/_151]]
  (1) Internal: Blas GEMM launch failed : a.shape=(128, 256), b.shape=(256, 256), m=128, n=256, k=256
	 [[node lstm_1/while/MatMul_4 (defined at /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:1072) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node lstm_1/while/MatMul_4:
 lstm_1/while/Identity_2 (defined at /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:2764)

Input Source operations connected to node lstm_1/while/MatMul_4:
 lstm_1/while/Identity_2 (defined at /gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py:2764)

Original stack trace for 'lstm_1/while/MatMul_4':
  File "model.py", line 203, in <module>
    main(sys.argv)
  File "model.py", line 168, in main
    prep_data(data, nl_word_to_idx, rl_word_to_idx, source_words, target_words, rl_idx_to_word)
  File "model.py", line 65, in prep_data
    encoder_outputs, state_h, state_c = encoder_lstm(enc_emb)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/layers/recurrent.py", line 488, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/layers/recurrent.py", line 2032, in call
    initial_state=initial_state)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/layers/recurrent.py", line 595, in call
    input_length=timesteps)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py", line 2764, in rnn
    swap_memory=True)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py", line 2723, in _step
    tuple(constants))
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/layers/recurrent.py", line 586, in step
    return self.cell.call(inputs, states, **kwargs)
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/layers/recurrent.py", line 1826, in call
    self.recurrent_kernel_i))
  File "/gpfs/runtime/opt/keras/2.1.3_py3/lib/python3.5/site-packages/Keras-2.1.3-py3.5.egg/keras/backend/tensorflow_backend.py", line 1072, in dot
    out = tf.matmul(x, y)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2647, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5925, in mat_mul
    name=name)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/gpfs/runtime/opt/tensorflow/1.14.0_gpu_py36/tf.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

